apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rx9d00ghh-python 
  janus-idp.io/tekton: rx9d00ghh-python
  backstage.io/kubernetes-id: rx9d00ghh-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rx9d00ghh-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml