apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rx9d00ghh-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rx9d00ghh-python 
  name: rx9d00ghh-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rx9d00ghh-python 
